
# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)


# src :
# https://mcpelauncher.readthedocs.io/en/latest/source_build/launcher.html
tasks:
  - init: cmake .
    before: sudo apt -y update && \
            sudo apt-get install --no-install-recommends g++  pkg-config clang cmake make git ca-certificates libssl-dev libpng-dev libx11-dev libxi-dev libcurl4-openssl-dev libudev-dev libevdev-dev libegl1-mesa-dev libssl-dev libasound2 qtbase5-dev qtwebengine5-dev qtdeclarative5-dev libqt5svg5-dev qml-module-qtquick2 qml-module-qtquick-layouts qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-window2 qml-module-qtquick-dialogs qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel qml-module-qtwebengine
    command: mkdir -p build && cd build && \
              CC=clang CXX=clang++ cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release -DJNI_USE_JNIVM=ON && \
              make -j$(getconf _NPROCESSORS_ONLN)

 


